############################# English ############################
[en]
languageName = "En"
title = "tuna"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
footer_content = "Tuna is envisioned to provide stable and reliable database access management service to global customers."
# copyright
copyright = "Copyright by tuna team"



############################# 简体中文 ############################
[zh-cn]
languageName = "简体中文"
title = "tuna"
contentDir = "content/chinese" # content/chinese
weight = 2
########### footer content ##########
footer_menu_left = "公司"
footer_menu_middle = "产品"
footer_menu_right = "支持"
footer_content = "Tuna致力于为全球用户提供稳定可靠的数据库权限管理服务"
# copyright
copyright = "知识产权由tuna团队所有"