# main menu
[[main]]
name = "Home"
url = "/"
weight = 1


[[main]]
name = "Contact"
url = "contact/"
weight = 2

[[main]]
name = "FAQ"
url = "faq/"
weight = 5

# footer menu left
[[footer_left]]
name = "About Us"
url = "#"

[[footer_middle]]
name = "Features"
url = "#"

[[footer_right]]
name = "FAQ"
url = "faq/"